server:
  port: 8080


spring:
  application:
    name: API-Gateway

ribbon:
  ReadTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaService:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-406566.okta.com/oauth2/aus2a96znsikQdEOt4x6
    clientId: 0oa2a96yehQVVcfDD4x6
    clientSecret: NQXh4OV2Tm5yKTBvBE9unmizwXT8QLmqGZjl1qkH
    audience: api://microservicesapplication


